-- 기준선(baseline) — 이 마이그레이션이 도입된 시점의 전체 스키마.
--
-- **운영 DB에서는 실행되지 않는다.** 이미 모든 테이블이 있는 상태에서 Flyway를
-- 도입했기 때문이다. `spring.flyway.baseline-on-migrate=true`가 비어 있지 않은
-- 스키마를 발견하면 이력 테이블에 "V1까지는 이미 적용됨"이라고 표시만 하고
-- 넘어간다. 그 뒤의 V2, V3...만 실제로 적용된다.
--
-- 이 파일이 필요한 이유는 **빈 DB에서 처음부터 세울 수 있어야** 하기 때문이다.
-- 서버를 새로 만들거나, 다른 사람이 clone해서 PostgreSQL로 띄울 때 이것 하나로
-- 스키마가 만들어진다.
--
-- 만들어진 방법: 운영 DB에서 `pg_dump --schema-only --no-owner --no-privileges`
-- 를 뜬 뒤 세션 설정(SET ...)과 소유자 지정을 걷어냈다. 그 스키마는
-- Hibernate의 ddl-auto=update가 만든 것에 deploy/sql/002~004를 손으로 적용한
-- 결과다 — 그 이력이 여기서 하나로 합쳐진다.
--
-- ⚠️ 이 파일은 앞으로 **수정하지 않는다.** 스키마를 바꾸려면 V2, V3... 를 새로
-- 만든다. 이미 적용된 마이그레이션을 고치면 체크섬이 어긋나 기동이 실패한다.

CREATE TABLE analysis_result (
    result_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    modified_at timestamp(6) without time zone,
    analyzed_date timestamp(6) without time zone,
    comparison_video_key character varying(255),
    feedback_content oid,
    issue_count integer,
    quality_json oid,
    quality_warning character varying(255),
    status character varying(255),
    top_issues_json oid,
    total_score integer,
    unreliable_note oid,
    unreliable_spans_json oid,
    log_id bigint,
    sync_map_json text,
    analysis_job_id character varying(255),
    CONSTRAINT analysis_result_status_check CHECK (((status)::text = ANY ((ARRAY['WAITING'::character varying, 'PROCESSING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[])))
);

ALTER TABLE analysis_result ALTER COLUMN result_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME analysis_result_result_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE assignment (
    assignment_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    modified_at timestamp(6) without time zone,
    due_date timestamp(6) without time zone,
    start_date timestamp(6) without time zone,
    title character varying(255),
    target_video_id bigint,
    team_id bigint,
    writer_id bigint
);

ALTER TABLE assignment ALTER COLUMN assignment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME assignment_assignment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE practice_log (
    log_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    modified_at timestamp(6) without time zone,
    assignment_id bigint,
    practice_video_id bigint,
    reference_video_id bigint,
    user_id bigint
);

ALTER TABLE practice_log ALTER COLUMN log_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME practice_log_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE push_subscription (
    push_subscription_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    modified_at timestamp(6) without time zone,
    user_id bigint NOT NULL,
    endpoint text,
    p256dh character varying(255),
    auth character varying(255)
);

ALTER TABLE push_subscription ALTER COLUMN push_subscription_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME push_subscription_push_subscription_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE team (
    team_id bigint NOT NULL,
    team_name character varying(255),
    leader_id bigint
);

ALTER TABLE team ALTER COLUMN team_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME team_team_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE users (
    user_id bigint NOT NULL,
    login_id character varying(255),
    nickname character varying(255),
    password character varying(255),
    provider character varying(255),
    provider_id character varying(255),
    team_id bigint,
    CONSTRAINT users_provider_check CHECK (((provider)::text = ANY ((ARRAY['LOCAL'::character varying, 'KAKAO'::character varying, 'NAVER'::character varying])::text[])))
);

ALTER TABLE users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE video (
    video_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    modified_at timestamp(6) without time zone,
    analysis_status smallint,
    choreography_end_sec double precision,
    choreography_start_sec double precision,
    content_type character varying(255),
    object_key character varying(255),
    type character varying(255),
    upload_completed boolean NOT NULL,
    uploader_id bigint,
    original_name character varying(255),
    CONSTRAINT video_analysis_status_check CHECK (((analysis_status >= 0) AND (analysis_status <= 3))),
    CONSTRAINT video_type_check CHECK (((type)::text = ANY ((ARRAY['REFERENCE'::character varying, 'PRACTICE'::character varying])::text[])))
);

ALTER TABLE video ALTER COLUMN video_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME video_video_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY analysis_result
    ADD CONSTRAINT analysis_result_pkey PRIMARY KEY (result_id);

ALTER TABLE ONLY assignment
    ADD CONSTRAINT assignment_pkey PRIMARY KEY (assignment_id);

ALTER TABLE ONLY practice_log
    ADD CONSTRAINT practice_log_pkey PRIMARY KEY (log_id);

ALTER TABLE ONLY push_subscription
    ADD CONSTRAINT push_subscription_pkey PRIMARY KEY (push_subscription_id);

ALTER TABLE ONLY team
    ADD CONSTRAINT team_pkey PRIMARY KEY (team_id);

ALTER TABLE ONLY team
    ADD CONSTRAINT uk55eo7kil7rg126ddxxkrjsf0h UNIQUE (leader_id);

ALTER TABLE ONLY practice_log
    ADD CONSTRAINT uk86yd87txsukuc9orwlm7lhrr7 UNIQUE (practice_video_id);

ALTER TABLE ONLY push_subscription
    ADD CONSTRAINT uk_push_subscription_endpoint UNIQUE (endpoint);

ALTER TABLE ONLY users
    ADD CONSTRAINT uk_users_provider_provider_id UNIQUE (provider, provider_id);

ALTER TABLE ONLY analysis_result
    ADD CONSTRAINT ukfx26go3xqiw5hk1uvgx6w1fj2 UNIQUE (log_id);

ALTER TABLE ONLY users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);

ALTER TABLE ONLY video
    ADD CONSTRAINT video_pkey PRIMARY KEY (video_id);

CREATE INDEX idx_push_subscription_user ON push_subscription USING btree (user_id);

ALTER TABLE ONLY analysis_result
    ADD CONSTRAINT fk6thia04l9ke5yhfbsu031a0n2 FOREIGN KEY (log_id) REFERENCES practice_log(log_id);

ALTER TABLE ONLY assignment
    ADD CONSTRAINT fk7s9krgqybbmyaciccd7opwd1y FOREIGN KEY (target_video_id) REFERENCES video(video_id);

ALTER TABLE ONLY team
    ADD CONSTRAINT fk9dboy6lc12vqc3wp619u9pey7 FOREIGN KEY (leader_id) REFERENCES users(user_id);

ALTER TABLE ONLY video
    ADD CONSTRAINT fkav6oukjptm9rwbvkof1xnkdab FOREIGN KEY (uploader_id) REFERENCES users(user_id);

ALTER TABLE ONLY assignment
    ADD CONSTRAINT fkdetrh6pu9ojx5htmct8jirhof FOREIGN KEY (team_id) REFERENCES team(team_id);

ALTER TABLE ONLY users
    ADD CONSTRAINT fkhn2tnbh9fqjqeuv8ehw5ple7a FOREIGN KEY (team_id) REFERENCES team(team_id);

ALTER TABLE ONLY practice_log
    ADD CONSTRAINT fkici3mt9u8ihvaxbupv4afu8o6 FOREIGN KEY (reference_video_id) REFERENCES video(video_id);

ALTER TABLE ONLY practice_log
    ADD CONSTRAINT fkkff6up02cf8bgqcfxehlkx2iu FOREIGN KEY (assignment_id) REFERENCES assignment(assignment_id);

ALTER TABLE ONLY assignment
    ADD CONSTRAINT fkmjj2pngywh6lbqw5e0ixb6cla FOREIGN KEY (writer_id) REFERENCES users(user_id);

ALTER TABLE ONLY practice_log
    ADD CONSTRAINT fkqm2bk5ufe3wldmosrj0esacvr FOREIGN KEY (user_id) REFERENCES users(user_id);

ALTER TABLE ONLY practice_log
    ADD CONSTRAINT fkr7pnppgv6g3v3vcpdwaas5sv4 FOREIGN KEY (practice_video_id) REFERENCES video(video_id);

ALTER TABLE ONLY push_subscription
    ADD CONSTRAINT push_subscription_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(user_id);
