-- 브라우저 푸시 구독 테이블.
--
-- 운영은 ddl-auto=validate라 이 스크립트를 **새 jar보다 먼저** 돌려야 한다.
-- 순서를 바꾸면 Hibernate 스키마 검증에 걸려 애플리케이션이 뜨지 않는다.
--
--   ssh odo 'sudo -u postgres psql -d dance_db' < deploy/sql/003-push-subscription.sql
--
-- 되돌리기:  DROP TABLE IF EXISTS push_subscription;

CREATE TABLE IF NOT EXISTS push_subscription (
    push_subscription_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at           timestamp(6),
    modified_at          timestamp(6),
    user_id              bigint NOT NULL REFERENCES users(user_id),
    -- 푸시 서비스 주소. 브라우저·공급자(FCM/Mozilla)마다 다르고 길어서 text다.
    endpoint             text,
    -- 종단간 암호화 키. 이게 있어서 중간의 푸시 서비스는 알림 내용을 못 본다.
    p256dh               varchar(255),
    auth                 varchar(255),
    -- 같은 브라우저가 다시 구독하면 같은 endpoint가 온다. 유니크로 막지 않으면
    -- 기기 하나가 구독을 계속 쌓아 알림이 중복 발송된다.
    CONSTRAINT uk_push_subscription_endpoint UNIQUE (endpoint)
);

-- 알림 발송은 항상 "이 사용자의 모든 기기"로 조회한다.
CREATE INDEX IF NOT EXISTS idx_push_subscription_user ON push_subscription(user_id);
